### ISSUE TITLE
upDATE

### ISSUE THREAD

**Issue by gamersalpha** [YunoHost-Apps/tvheadend_ynh#2]
hELLO 
Do u update, can i install this program ?

**Comment by sy6sy2** [comment]
Hello,
Yes I update this app. But currently the website where TVHeadend debs files is down.
I will update to the latest version as soon as possible.

**Comment by gamersalpha** [comment]
j'ai tenté une install je suis bloqué sur l'identifiant rien ne fonctionne

**Comment by sy6sy2** [comment]
L'installation s'est bien passée ? Quand vous dites "bloqué sur l'identifiant" c'est au niveau da la page web de TVHEadend ?

**Comment by gamersalpha** [comment]
i m stuck on this : 
![image](https://user-images.githubusercontent.com/32466950/81409225-0b7e1180-913f-11ea-85d9-cc7d7db57f73.png)

je ne sais pas qu'elle identifiant utiliser

**Comment by sy6sy2** [comment]
Il faut utiliser l'identifiant et le mot de passe que vous avez choisi lors de l'installation (le login superuser et le mot de passe superuser)

**Comment by gamersalpha** [comment]
c'est ce que je fait mais ça ne marche pas, j'ai désinstaller et reinstaller en faisant bien attention 
ça prend pas

**Comment by sy6sy2** [comment]
Hum étrange. en SSH vous pouvez vérifier le login et mot de passe en faisant
```
sudo cat /home/hts/.hts/tvheadend/superuser
```

**Comment by gamersalpha** [comment]
j'ai copier coller le résultat ça ne marche pas

**Comment by sy6sy2** [comment]
Ah je crois que je sais. Est-ce que vous pouvez essayer directement avec l'adresse IP à la place du nom de domaine ?

**Comment by gamersalpha** [comment]
je peux pas si je met l'ip ça me renvoi directe sur la page admin de yunohost

**Comment by sy6sy2** [comment]
Avec le port aussi ?
Chez moi avec ça ça fonctionne : `192.168.1.20:9981`

Edit: J'ai l'impression que c'est le `https` qui fout la merde...

**Comment by gamersalpha** [comment]
ça marche avec l'ip : 
![image](https://user-images.githubusercontent.com/32466950/81412128-ae388f00-9143-11ea-887b-f2579f75ef7a.png)

**Comment by sy6sy2** [comment]
Cool ! Je vais essayer de regarder si je peux le faire fonctionner avec le domaine. En vrai je ne me rappelle même plus si ça a fonctionné un jour xD
J'avoue que je passe toujours pas l'IP...

**Comment by gamersalpha** [comment]
pas pratique pour y accéder depuis internet ?

zut du coup je retrouve plus ma clé tnt

**Comment by gamersalpha** [comment]
t'a pas un chat un discord pour discuter ?

**Comment by gamersalpha** [comment]
j'ai redemmarer mon serveur mais ça ne semble plus démmarer tvheadend i lfaut attendre longtemps ?

**Comment by sy6sy2** [comment]
Hum, de mémoire il doit se lancer au démarrage.
