### ISSUE TITLE
The automatic test (CI) fails because the install hangs forever for some reason ...

### ISSUE THREAD

**Issue by alexAubin** [YunoHost-Apps/tvheadend_ynh#5]
c.f. https://ci-apps.yunohost.org/ci/job/183

Unfortunately the only logs available are : 

```
>> Installation in a sub path... [Test 2/8]
A LXC container is already running.
Working time: 1 second (19:20:48).
!!! Timeout reached (180 min). !!!
!!! Package check was too long, its execution was aborted. !!! (PCHECK_AVORTED)
```

But do you have any idea why the install may hang indefinitely ? 

In parallel I just proposed to re-flag the app as level 0 because it's been months since we didn't have an actual test result for this app because of this issue :/ 

https://github.com/YunoHost/apps/pull/1028

**Comment by sy6sy2** [comment]
Hi, sorry it's been a while but I finally took the time to update and fix this app.
I performed some local test and this is what should work:

* Upgrade from last version
* Install, remove, upgrade, backup and restore

I still have some issues to access the web interface from the YunoHost panel, I need to work on it. But users can still use IPv4 with 9981 port to access the app.
